blueprint:
  name: Lichtsteuerung mit Bewegung und Helligkeit
  description: Schaltet das Licht basierend auf einem Bewegungssensor und Helligkeitsschwelle ein und h채lt es bei Bewegung an.
  domain: automation
  input:
    licht:
      name: Licht
      description: W채hle das Licht, das geschaltet werden soll.
      selector:
        entity:
          domain: light
    brightness:
      name: Helligkeit des Lichts in %
      description: Helligkeit des Lichts beim Einschalten (0-100)
      default: 100
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
    bewegungssensor:
      name: Bewegungssensor
      description: W채hle den Bewegungssensor, der das Licht steuert.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    lux_sensor:
      name: Helligkeitssensor
      description: W채hle den Lux-/Helligkeitssensor.
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    lux_threshold:
      name: Lux-Schwellenwert
      description: Maximaler Lux-Wert, unter dem das Licht eingeschaltet wird (0-100)
      default: 30
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "lx"
          mode: slider
    wait_time:
      name: Wartezeit in Sekunden
      description: Wie lange das Licht nach der letzten Bewegung anbleiben soll.
      default: 60
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: "Sekunden"
          mode: slider

trigger:
  - platform: state
    entity_id: !input bewegungssensor
    to: "on"

condition:
  - condition: numeric_state
    entity_id: !input lux_sensor
    below: !input lux_threshold

action:
  - service: light.turn_on
    target:
      entity_id: !input licht
    data:
      brightness_pct: !input brightness

  - wait_for_trigger:
      - platform: state
        entity_id: !input bewegungssensor
        to: "off"
        for:
          seconds: !input wait_time
    continue_on_timeout: false

  - service: light.turn_off
    target:
      entity_id: !input licht

mode: restart
